120 gsd error metrics throw if reference did not detect a gs
mobilise-d/mobgap pull request #127
Opened 2024-04-10 09:55 UTC by a-mosquito

2024-04-10 09:55 UTC, a-mosquito commented
I added a `zero_division_hint` parameter to the `calculate_unmatched_gsd_performance_metrics` function. I named it differently than the parameter used for the basic evaluation functions as it behaves differently
- set to `False`: warning is suppressed and values are set to nan
- set to "warn": warning is raised and values are set to nan
- set to "raise": `ZeroDivisionError` is raised

(comp. to `zero_division` parameter from f1-score etc: result is either set to 0, 1, or warning is raised)

2024-04-15 09:05 UTC, AKuederle requested changes
Small wording comment. Other than that ready to merge

2024-04-15 09:05 UTC, AKuederle commented on mobgap/gsd/evaluation.py
> +        If set to False, the warning is suppressed and the affected metrics are set to NaN.
Can we have the option to use "NaN" instead of False (so to make it consistent with the other option)

2024-04-15 09:05 UTC, AKuederle commented on mobgap/gsd/evaluation.py
> +        If set to False, the warning is suppressed and the affected metrics are set to NaN.
And can you specify in what scope that will be applied. Very specifically we safeguard against the reference_gs_duration_s == 0

2024-04-17 08:11 UTC, AKuederle commented on mobgap/gsd/evaluation.py
> +        If set to False, the warning is suppressed and the affected metrics are set to NaN.
Sorry I wasn't clear on that one. Can we actually use the value np.nan? In the other case, when we put in a 1 th output will be 1. So here it seems natural if we put np.nan, we get np.nan. Or is that a bad idea?

2024-04-17 13:10 UTC, AKuederle approved these changes

2024-04-17 13:10 UTC, merged